export const contactData =  [
    {
      label: "First Name",
      name: "firstName",
      type: "text",
      placeholder: "e.g. John",
      required: true,
      errorMessage: "Please enter your first name.",
      className: "first-name-input",
    },
    {
      label: "Last Name",
      name: "lastName",
      type: "text",
      placeholder: "e.g. Doe",
      required: true,
      errorMessage: "Please enter your last name.",
      className: "last-name-input",
    },
    {
      label: "Phone Number",
      name: "phone",
      type: "text",
      placeholder: "e.g. 123-456-7890",
      required: true,
      errorMessage: "Please enter your phone number.",
      className: "phone-input",
    },
    {
      label: "Email ID",
      name: "email",
      type: "text",
      placeholder: "e.g. example@example.com",
      required: true,
      errorMessage: "Please enter your email ID.",
      className: "email-input",
    },
    {
      label: "Address",
      name: "address",
      type: "text",
      placeholder: "e.g. 123 Main Street",
      required: true,
      errorMessage: "Please enter your address.",
      className: "address-input",
    },
    {
      label: "Subject",
      name: "subject",
      type: "text",
      placeholder: "e.g. Material I purchased is not delivered yet...",
      required: true,
      errorMessage: "Please enter a subject.",
      className: "subject-input",
    },
  ];